services:
  backend:
    build: ./backend
    ports:
      - "8081:8080" # changed from 8080 cuz of Cliper
    container_name: paf-backend
    # environment:
    #   SPRING_DATA_MONGODB_URI: mongodb+srv://chamupathijayanath010_db_user:ZtzcNSYqPTDTDXnt@pafcluster.whoyvn5.mongodb.net/pafdb?retryWrites=true&w=majority

  frontend:
    build: ./frontend
    ports:
      - "5174:5173" # changed from 5173 cuz of Cliper
    depends_on:
      - backend
    container_name: paf-frontendd