# =============================================
# Smart Facility Booking System - Config
# =============================================

# Server
server.port=8080
spring.application.name=facility-booking-system

# MongoDB
spring.data.mongodb.uri=mongodb+srv://chamupathijayanath010_db_user:ZtzcNSYqPTDTDXnt@pafcluster.whoyvn5.mongodb.net/pafdb?retryWrites=true&w=majority&appName=pafCluster
spring.data.mongodb.database=pafdb

# JWT
app.jwt.secret=S3cur3F4c1l1tyB00k1ngS3cr3tK3yF0rJWT2024ProductionR3adyX9m4K2p7V1n6L0q8T3w5Z
app.jwt.expiration=86400000

# OAuth2 Google
spring.security.oauth2.client.registration.google.client-id=1034086416183-rv6kc2eut9bse18ge8437fstics0eok0.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# File Upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB
app.upload.dir=uploads

# Logging
logging.level.com.facility=DEBUG
logging.level.org.springframework.security=WARN

# CORS
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000
app.cors.allowed-origin-patterns=http://localhost:*,http://127.0.0.1:*,http://[::1]:*

# Frontend URL (for OAuth2 redirect)
app.frontend.url=http://localhost:5173
