server.port=8080

# MongoDB
spring.data.mongodb.uri=mongodb+srv://chamupathijayanath010_db_user:ZtzcNSYqPTDTDXnt@pafcluster.whoyvn5.mongodb.net/pafdb?retryWrites=true&w=majority&appName=pafCluster


# File upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB

# Upload directory
app.upload.dir=./uploads/

# Logging
logging.level.com.ticketsystem=DEBUG
